//HERE IS WHERE YOUR SQL SCRIPTS WILL BE PLACED



var db = require("../models");
// const sequelize = require("sequelize");
  // db.sequelize.query("INSERT INTO stocks (updatedAt, createdAt, fulfillment_date, price, repeatItem, title1, title2, title3, line04, line05, line06, line07, line08, line09, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, imageURL) VALUES (CURDATE(),CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),8.00,1,'Steak wrapped veggies with side salad','','Regular','','Keto friendly, low carb','Calories: 298.3','Protein- 35.8g','Carbs- 10.7g','Fats- 32g','','Steak','Bell pepper','Asparagus','','','','','','','','');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO stocks (updatedAt, createdAt, fulfillment_date, price, repeatItem, title1, title2, title3, line04, line05, line06, line07, line08, line09, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, imageURL) VALUES (CURDATE(),CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),8.00,1,'Keto/ Low Carb Pizza Casserole & Side salad','','Regular','','Calories 147 Calories from Fat 90','% Daily Value*','Total Fat 10g 15%','Saturated Fat 4g 20%' ,'Polyunsaturated Fat 1g','Monounsaturated Fat 2g','Cholesterol 69mg','Sodium 194mg','','-Uncured pepperoni','-Cauliflower','-Mozzarella cheese','-Tomatoes','','can offer Vegetarian option, just ask','','');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO stocks (updatedAt, createdAt, fulfillment_date, price, repeatItem, title1, title2, title3, line04, line05, line06, line07, line08, line09, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, imageURL) VALUES (CURDATE(),CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),8.00,1,'Garlic Chicken stir fry','','Regular','','Calories: 316.2','Carbs: 23.6','Fats: 6.5','Protein: 43.9','','-Chicken','-Broccoli','-Bell pepper','-Mushrooms','','','','','','','','');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO stocks (updatedAt, createdAt, fulfillment_date, price, repeatItem, title1, title2, title3, line04, line05, line06, line07, line08, line09, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, imageURL) VALUES (CURDATE(),CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),8.00,1,'Basil Pesto Chicken, Brn Rice & Mixed Veggies','','Regular','','Calories: 560','Carbs: 36.5','Fats: 31.2','Protein:47.2','','-Basil Pesto','-Chicken','-Mixed Veggies(may change weekly)','-Brown rice','','','','','','','','');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO stocks (updatedAt, createdAt, fulfillment_date, price, repeatItem, title1, title2, title3, line04, line05, line06, line07, line08, line09, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, imageURL) VALUES (CURDATE(),CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),4.00,1,'In Season Fruit Cups','','Regular','','Will change weekly','','','','','','','','','','','','','','','','');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO Customers (updatedAt, createdAt, firstname, lastname, phonenumber, email, password, address1, address2, address3, city, state, zip) VALUES (CURDATE(),CURDATE(),'Anthony','Duncan','281-555-1234','test@gmail.com','password123','1234 test rd','Apt 001', '', 'Austin','TX','78750');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO Customers (updatedAt, createdAt, firstname, lastname, phonenumber, email, password, address1, address2, address3, city, state, zip) VALUES (CURDATE(),CURDATE(),'Justin','Mozley','281-500-1234','test1@gmail.com','password123','1120 test ln','Apt 002', '', 'Buda','TX','78610');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO Customers (updatedAt, createdAt, firstname, lastname, phonenumber, email, password, address1, address2, address3, city, state, zip) VALUES (CURDATE(),CURDATE(),'Owais','Jamil','281-550-1234','test2@gmail.com','password123','1234 test ave','', '', 'Kyle','TX','78610');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO Customers (updatedAt, createdAt, firstname, lastname, phonenumber, email, password, address1, address2, address3, city, state, zip) VALUES (CURDATE(),CURDATE(),'Kevin','Henderson','281-000-1234','test3@gmail.com','password123','1235 test rd','Apt 004', '', 'Buda','TX','78610');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'1',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'1',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'1',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'1',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'2',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'2',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'2',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO orders (updatedAt, createdAt, unique_id, order_date, fulfillment_date, order_type, delivery_date, order_status) VALUES (CURDATE(),CURDATE(),'2',now(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'Delivery',(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),'In Progress');").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),1,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),2,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),3,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),4,2,16,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),5,3,12,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),2,2,16,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),3,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),4,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO what_ordereds (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),5,4,16,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),1,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),2,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (09 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),4,2,16,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),1,1,(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),5,3,12,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),3,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (16 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),4,1,8,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (23 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  // db.sequelize.query("INSERT INTO order_histories (updatedAt, createdAt, unique_id, order_id, fulfillment_date, meal_id, quantity, price, order_date, delivery_date) VALUES (CURDATE(),CURDATE(),2,2,(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)),5,4,16,CURDATE(),(SELECT DATE_ADD(CURDATE(), INTERVAL (30 - IF(DAYOFWEEK(CURDATE())=1, 08, DAYOFWEEK(CURDATE()))) DAY)));").then(([results, metadata]) => {   });
  